services:
  database:
    image: 'postgres:16.4'
    ports:
      - '5432:5432'
    environment:
      - 'POSTGRES_DB=app_db'
      - 'POSTGRES_USER=app_user'
      - 'POSTGRES_PASSWORD=secret'

  mail_server:
    image: 'mailhog/mailhog'
    ports:
      - '1025:1025'
      - '8025:8025'
